### ISSUE TITLE
Is it possible to specify a bed file in Muse 2

### ISSUE THREAD

**Issue by harrymatthews50** [wwylab/MuSE#24]
Thank you for the great utility. Muse call  in version 1 supported specifying genomic regions of interest via a bed file. (option -l). Am I correct this has been removed in version 2? Is there any way to specify genomic regions with version 2?

**Comment by jiyunmaths** [comment]
@harrymatthews50, thank you for your interests in MuSE 2. We indeed removed this option in MuSE 2 based on the following reasons. After detecting candidate variants, MuSE needs to fit a beta distribution/Gaussian Mixture Model for WES and WGS respectively to separate true variants from background noise. The candidate variants from the whole genome/exome can provide a more accurate fitting than only including the ones from a specific region. Also, MuSE 2 is significantly fast so that it can process the whole genome in a very reasonable time. We are open to hearing any specific needs for running one chromosome at a time and help adapt the code if necessary.

**Comment by jiyunmaths** [comment]
@harrymatthews50 MuSE 1 included the option to parallelize processing across different chromosomes, which was crucial for WGS data to avoid long processing times. However, with the more efficient parallel computing strategy in MuSE 2, this option is no longer necessary.
